{% set name = "precice" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/precice/precice/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 76ec6ee0d1a66f6f3d3d2d11f03cfc5aa7ef4d9e5deb9b7a4b4455ec7f796c00

build:
  number: 9
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('precice', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
    - make
    - pkgconfig
    - python
    - numpy
  host:
    - python
    - libboost-devel
    - eigen
    - fmt
    - libxml2
    - nlohmann_json
    - numpy
    - petsc
    - {{ mpi }}
  run:
    - python

test:
  commands:
    - test -f ${PREFIX}/lib/libprecice.so  # [linux]

about:
  home: https://precice.org/
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A coupling library for partitioned multi-physics simulations, including, but not restricted to fluid-structure interaction and conjugate heat transfer simulations.
  description: |
    preCICE stands for Precise Code Interaction Coupling Environment. Its
    main component is a library that can be used by simulation programs
    to be coupled together in a partitioned way, enabling multi-physics
    simulations, such as fluid-structure interaction.
  doc_url: https://precice.org/docs.html
  dev_url: https://github.com/precice/precice

extra:
  recipe-maintainers:
    - IshaanDesai
    - jan-janssen
