schema_version: 1

context:
  name: precice
  version: "3.4.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/precice/precice/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 1155178da7271c404947d1ff64b6e5028a82575fd532baa26bd6418de5ef2623

build:
  number: 4
  skip: win

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('fortran') }}
    - ${{ stdlib("c") }}
    - cmake
    - make
    - pkgconfig
    - python
    - numpy
  host:
    - python
    - libboost-devel
    - eigen
    - fmt
    - libxml2-devel
    - nlohmann_json
    - numpy
    - petsc
    - ${{ mpi }}
  run:
    - python
  run_exports:
    - ${{ pin_subpackage('precice', upper_bound='x.x') }}

tests:
  - script:
      - if: linux
        then: test -f ${PREFIX}/lib/libprecice.so

about:
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: A coupling library for partitioned multi-physics simulations, including, but not restricted to fluid-structure interaction and conjugate heat transfer simulations.
  description: |
    preCICE stands for Precise Code Interaction Coupling Environment. Its
    main component is a library that can be used by simulation programs
    to be coupled together in a partitioned way, enabling multi-physics
    simulations, such as fluid-structure interaction.
  homepage: https://precice.org/
  repository: https://github.com/precice/precice
  documentation: https://precice.org/docs.html

extra:
  recipe-maintainers:
    - IshaanDesai
    - jan-janssen
